### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by robertklaus** [lucky-luky/GDWWS2021_DorrenbachKlausSetyarini#2]
Hallo Mario,

wir hätten die Frage ob wir essential use cases oder concrete use cases erstellen sollen? Oder beides?

Gruß,
Team DorrenbachKlausSetyarini

**Comment by mariofaske** [comment]
Hallo, 

da geben wir euch nichts vor, das liegt in eurer Entscheidung wie detailliert euer use case sein muss um die relevanten Funktionen eures Webservices aufzuzeigen.

**Comment by robertklaus** [comment]
Hallo Mario,

Danke für die schnelle Antwort! 
Wir haben nun welche erstellt. Sind diese vom Aufbau korrekt?

--> https://github.com/lucky-luky/GDWWS2021_DorrenbachKlausSetyarini/wiki/13.-Use-Cases



Gruß,
Team DorrenbachKlausSetyarini

**Comment by mariofaske** [comment]
Hallo,

am besten ihr formuliert die use cases auch nochmal in Textform (was ja eigentlich der erste schritt wäre ;) )

**Comment by robertklaus** [comment]
Hallo Mario,

wir haben nun die Use Cases auch in textueller Form umgesetzt. 
Könntest du uns dazu Feedback geben?


Gruß,
Team DorrenbachKlausSetyarini

**Comment by mariofaske** [comment]
Klingt soweit alles verständlich. Ihr habt ja für das Video nur 10 Minuten, also schaut, dass ihr einen Use case auswählt welcher auf eure Anwendungslogik bzw. den Mehrwert eures Systems fokussiert ist.
