### ISSUE TITLE
Kickoff Workshop Dienstag 16.02.2021

### ISSUE THREAD

**Issue by lucky-luky** [lucky-luky/GDWWS2021_DorrenbachKlausSetyarini#3]
Hallo Mario,

genau an dem Tag und Uhrzeit schreibe ich Klausur für ein anderes Modul. Dürfte ich durch die Teammitglieder vertreten werden?

Viele Grüße
Luky

**Comment by mariofaske** [comment]
Ja, kannst du, das ist kein Problem.

**Comment by lucky-luky** [comment]
> Ja, kannst du, das ist kein Problem.

Danke sehr.
