### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by robertklaus** [lucky-luky/GDWWS2021_DorrenbachKlausSetyarini#4]
Hallo Mario,

Sollen wir im Video nur den Code erklären anhand eines Use Cases oder wie in dem Dokument auf Seite 3 erklärt wird nur die Artefakte im Repositorium?

https://th-koeln.sciebo.de/s/hD0HnFXS9H79sQV

**Comment by mariofaske** [comment]
Den lauffähigen Webservice erklärt ihr anhand eines Anwendungsfalls und dann könnt ihr danach auf Codeausschnitte im Repository eingehen und zum Beispiel signifikante Anwendungslogik erklären.

**Comment by lucky-luky** [comment]
Hallo Mario,

wir haben das Video aufgenommen. Allerdings dauert das Video etwas länger, und zwar ca. 16 Minuten.

 VG

**Comment by mariofaske** [comment]
Das ist aber deutlich zu viel. Die Forderung war 10 min. Ein bis zwei Minuten drüber könnten wir noch verschmerzen, aber sechs ist auch denen unfair gegenüber, die sich an die 10 Minuten halten.

Beschränkt euch auf das wesentliche/wichtige(UseCase, Code, Iterationen, Reflexion), ihr habt ja noch das Wiki wo ihr alles dokumentiert habt.

**Comment by lucky-luky** [comment]
Hallo Mario,

9 Minuten dauert das Video.

VG
